// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.ShadowMonarch;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.ShadowMonarch.UI;

[GenerateTypedNameReferences]
public sealed partial class ShadowMonarchStatsWindow : FancyWindow
{
    public event Action<ShadowMonarchStat>? OnAllocateStat;

    public ShadowMonarchStatsWindow()
    {
        RobustXamlLoader.Load(this);

        StrengthButton.OnPressed += _ => OnAllocateStat?.Invoke(ShadowMonarchStat.Strength);
        AgilityButton.OnPressed += _ => OnAllocateStat?.Invoke(ShadowMonarchStat.Agility);
        ResistanceButton.OnPressed += _ => OnAllocateStat?.Invoke(ShadowMonarchStat.Resistance);
        IntellectButton.OnPressed += _ => OnAllocateStat?.Invoke(ShadowMonarchStat.Intellect);
    }

    public void UpdateState(ShadowMonarchStatsState state)
    {
        PointsLabel.Text = Loc.GetString("shadow-monarch-stats-points", ("points", state.StatPoints));
        KillsLabel.Text = Loc.GetString("shadow-monarch-stats-kills", ("kills", state.KillCount));

        // Strength
        StrengthLevel.Text = $"{state.Strength}/{state.MaxStatLevel}";
        StrengthEffect.Text = Loc.GetString("shadow-monarch-stat-strength-effect", ("damage", state.BonusDamage));
        StrengthButton.Disabled = state.StatPoints <= 0 || state.Strength >= state.MaxStatLevel;

        // Agility
        AgilityLevel.Text = $"{state.Agility}/{state.MaxStatLevel}";
        AgilityEffect.Text = Loc.GetString("shadow-monarch-stat-agility-effect", ("speed", state.BonusSpeed));
        AgilityButton.Disabled = state.StatPoints <= 0 || state.Agility >= state.MaxStatLevel;

        // Resistance
        ResistanceLevel.Text = $"{state.Resistance}/{state.MaxStatLevel}";
        ResistanceEffect.Text = Loc.GetString("shadow-monarch-stat-resistance-effect", ("hp", state.BonusHp), ("stamina", state.BonusStamina));
        ResistanceButton.Disabled = state.StatPoints <= 0 || state.Resistance >= state.MaxStatLevel;

        // Intellect
        IntellectLevel.Text = $"{state.Intellect}/{state.MaxStatLevel}";
        IntellectEffect.Text = Loc.GetString("shadow-monarch-stat-intellect-effect", ("mana", state.BonusMana), ("army", state.BonusArmy));
        IntellectButton.Disabled = state.StatPoints <= 0 || state.Intellect >= state.MaxStatLevel;

        // Mana bar
        ManaLabel.Text = Loc.GetString("shadow-monarch-stats-mana", ("current", (int) state.ShadowMana), ("max", (int) state.MaxShadowMana));
        ManaBar.MaxValue = state.MaxShadowMana;
        ManaBar.Value = state.ShadowMana;
    }
}
