// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.Botany.Genes;
using Content.Shared._Capibara.Botany.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class DnaManipulatorWindow : FancyWindow
{
    public event Action<int>? OnExtractGene;
    public event Action? OnInsertGene;
    public event Action? OnEjectSeed;
    public event Action? OnEjectDisk;

    public DnaManipulatorWindow()
    {
        RobustXamlLoader.Load(this);
        EjectSeedButton.OnPressed += _ => OnEjectSeed?.Invoke();
        EjectDiskButton.OnPressed += _ => OnEjectDisk?.Invoke();
        InsertButton.OnPressed += _ => OnInsertGene?.Invoke();
    }

    public void UpdateState(DnaManipulatorBuiState state)
    {
        // Seed section
        if (state.HasSeed)
        {
            SeedNameLabel.Text = state.SeedSpeciesName ?? "???";
            SeedNameLabel.Modulate = Color.White;
            InstabilityLabel.Text = Loc.GetString("capibara-seed-analyzer-instability",
                ("value", $"{state.Instability:F0}"));
            InstabilityLabel.Modulate = InstabilityColor(state.Instability);
            InstabilityLabel.Visible = true;
        }
        else
        {
            SeedNameLabel.Text = Loc.GetString("capibara-dna-manipulator-no-seed");
            SeedNameLabel.Modulate = Color.FromHex("#666666");
            InstabilityLabel.Visible = false;
        }

        // Gene slots with extract buttons
        GeneSlotsContainer.RemoveAllChildren();
        for (var i = 0; i < state.GeneSlots.Count; i++)
        {
            GeneSlotsContainer.AddChild(CreateGeneSlotRow(i, state.GeneSlots[i],
                state.HasDisk && !state.DiskHasGene));
        }

        // Disk section
        if (state.HasDisk)
        {
            if (state.DiskHasGene)
            {
                DiskStatusLabel.Text = state.DiskGeneName ?? "???";
                DiskStatusLabel.Modulate = GetRarityColor(state.DiskGeneRarity ?? PlantGeneRarity.Common);
            }
            else
            {
                DiskStatusLabel.Text = Loc.GetString("capibara-dna-manipulator-disk-blank");
                DiskStatusLabel.Modulate = Color.FromHex("#555566");
            }
            DiskIntegrityLabel.Text = Loc.GetString("capibara-dna-manipulator-disk-integrity",
                ("value", $"{state.DiskIntegrity:F0}"));
            DiskIntegrityLabel.Modulate = state.DiskIntegrity > 50 ? Color.FromHex("#44BB44") : Color.FromHex("#BB4444");
            DiskIntegrityLabel.Visible = true;
        }
        else
        {
            DiskStatusLabel.Text = Loc.GetString("capibara-dna-manipulator-no-disk");
            DiskStatusLabel.Modulate = Color.FromHex("#666666");
            DiskIntegrityLabel.Visible = false;
        }

        InsertButton.Disabled = !state.HasSeed || !state.HasDisk || !state.DiskHasGene;
    }

    private PanelContainer CreateGeneSlotRow(int index, GeneSlotData data, bool canExtract)
    {
        var panel = new PanelContainer { Margin = new Thickness(0, 1) };

        Color bgColor;
        if (data.Locked)
            bgColor = Color.FromHex("#1A1A1A");
        else if (data.GeneId != null)
            bgColor = GetRarityBg(data.Rarity ?? PlantGeneRarity.Common);
        else
            bgColor = Color.FromHex("#12121A");

        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = bgColor,
            BorderColor = data.GeneId != null ? GetRarityColor(data.Rarity ?? PlantGeneRarity.Common).WithAlpha(0.3f) : Color.FromHex("#222222"),
            BorderThickness = new Thickness(3, 0, 0, 0),
            ContentMarginLeftOverride = 8, ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3, ContentMarginRightOverride = 4,
        };

        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        box.AddChild(new Label { Text = $"{index + 1}.", MinWidth = 20, Modulate = Color.FromHex("#666666") });

        if (data.Locked)
        {
            box.AddChild(new Label { Text = Loc.GetString("capibara-seed-analyzer-slot-locked"), Modulate = Color.FromHex("#554444"), HorizontalExpand = true });
        }
        else if (data.GeneId == null)
        {
            box.AddChild(new Label { Text = Loc.GetString("capibara-seed-analyzer-slot-empty"), Modulate = Color.FromHex("#444455"), HorizontalExpand = true });
        }
        else
        {
            var c = GetRarityColor(data.Rarity ?? PlantGeneRarity.Common);
            box.AddChild(new Label { Text = $"{data.GeneName} [{data.Rarity}]", Modulate = c, HorizontalExpand = true });

            if (canExtract)
            {
                var idx = index;
                var btn = new Button
                {
                    Text = Loc.GetString("capibara-dna-manipulator-extract"),
                    Margin = new Thickness(4, 0, 0, 0),
                };
                btn.OnPressed += _ => OnExtractGene?.Invoke(idx);
                box.AddChild(btn);
            }
        }

        panel.AddChild(box);
        return panel;
    }

    private static Color GetRarityColor(PlantGeneRarity r) => r switch
    {
        PlantGeneRarity.Common => Color.FromHex("#BBBBBB"),
        PlantGeneRarity.Uncommon => Color.FromHex("#44CC44"),
        PlantGeneRarity.Rare => Color.FromHex("#4499FF"),
        PlantGeneRarity.Legendary => Color.FromHex("#FF9944"),
        _ => Color.White,
    };

    private static Color GetRarityBg(PlantGeneRarity r) => r switch
    {
        PlantGeneRarity.Common => Color.FromHex("#161618"),
        PlantGeneRarity.Uncommon => Color.FromHex("#14201A"),
        PlantGeneRarity.Rare => Color.FromHex("#141A24"),
        PlantGeneRarity.Legendary => Color.FromHex("#201A14"),
        _ => Color.FromHex("#161618"),
    };

    private static Color InstabilityColor(float i)
    {
        if (i <= 25f) return Color.FromHex("#44BB44");
        if (i <= 50f) return Color.FromHex("#BBBB44");
        if (i <= 75f) return Color.FromHex("#CC7733");
        return Color.FromHex("#CC3333");
    }
}
