// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.Botany.Genes;
using Content.Shared._Capibara.Botany.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class GeneSplicerWindow : FancyWindow
{
    public event Action? OnSplice;
    public event Action? OnEjectA;
    public event Action? OnEjectB;

    public GeneSplicerWindow()
    {
        RobustXamlLoader.Load(this);
        EjectAButton.OnPressed += _ => OnEjectA?.Invoke();
        EjectBButton.OnPressed += _ => OnEjectB?.Invoke();
        SpliceButton.OnPressed += _ => OnSplice?.Invoke();
    }

    public void UpdateState(GeneSplicerBuiState state)
    {
        // Disk A display
        if (!state.HasDiskA)
        {
            DiskALabel.Text = Loc.GetString("capibara-gene-splicer-no-disk");
            DiskALabel.Modulate = Color.FromHex("#555566");
            DiskAIntegrityLabel.Visible = false;
        }
        else if (!state.DiskAHasGene)
        {
            DiskALabel.Text = Loc.GetString("capibara-gene-splicer-empty-disk");
            DiskALabel.Modulate = Color.FromHex("#888888");
            DiskAIntegrityLabel.Text = Loc.GetString("capibara-dna-manipulator-disk-integrity", ("value", $"{state.DiskAIntegrity:F0}"));
            DiskAIntegrityLabel.Modulate = state.DiskAIntegrity > 50 ? Color.FromHex("#44BB44") : Color.FromHex("#BB4444");
            DiskAIntegrityLabel.Visible = true;
        }
        else
        {
            DiskALabel.Text = state.GeneNameA ?? "???";
            DiskALabel.Modulate = GetRarityColor(state.RarityA ?? PlantGeneRarity.Common);
            DiskAIntegrityLabel.Text = Loc.GetString("capibara-dna-manipulator-disk-integrity", ("value", $"{state.DiskAIntegrity:F0}"));
            DiskAIntegrityLabel.Modulate = state.DiskAIntegrity > 50 ? Color.FromHex("#44BB44") : Color.FromHex("#BB4444");
            DiskAIntegrityLabel.Visible = true;
        }

        // Disk B display
        if (!state.HasDiskB)
        {
            DiskBLabel.Text = Loc.GetString("capibara-gene-splicer-no-disk");
            DiskBLabel.Modulate = Color.FromHex("#555566");
            DiskBIntegrityLabel.Visible = false;
        }
        else if (!state.DiskBHasGene)
        {
            DiskBLabel.Text = Loc.GetString("capibara-gene-splicer-empty-disk");
            DiskBLabel.Modulate = Color.FromHex("#888888");
            DiskBIntegrityLabel.Text = Loc.GetString("capibara-dna-manipulator-disk-integrity", ("value", $"{state.DiskBIntegrity:F0}"));
            DiskBIntegrityLabel.Modulate = state.DiskBIntegrity > 50 ? Color.FromHex("#44BB44") : Color.FromHex("#BB4444");
            DiskBIntegrityLabel.Visible = true;
        }
        else
        {
            DiskBLabel.Text = state.GeneNameB ?? "???";
            DiskBLabel.Modulate = GetRarityColor(state.RarityB ?? PlantGeneRarity.Common);
            DiskBIntegrityLabel.Text = Loc.GetString("capibara-dna-manipulator-disk-integrity", ("value", $"{state.DiskBIntegrity:F0}"));
            DiskBIntegrityLabel.Modulate = state.DiskBIntegrity > 50 ? Color.FromHex("#44BB44") : Color.FromHex("#BB4444");
            DiskBIntegrityLabel.Visible = true;
        }

        // Result / recipe display
        if (state.CanSplice)
        {
            ResultLabel.Text = Loc.GetString("capibara-gene-splicer-result", ("gene", state.ResultGeneName ?? "???"));
            ResultLabel.Modulate = Color.FromHex("#FF9944");
            ChanceLabel.Text = Loc.GetString("capibara-gene-splicer-chance", ("chance", $"{state.SuccessChance * 100:F0}"));
            ChanceLabel.Modulate = state.SuccessChance > 0.4f ? Color.FromHex("#44BB44") : Color.FromHex("#BB4444");
            ChanceLabel.Visible = true;
        }
        else
        {
            if (state.DiskAHasGene && state.DiskBHasGene)
                ResultLabel.Text = Loc.GetString("capibara-gene-splicer-no-recipe");
            else
                ResultLabel.Text = "";
            ResultLabel.Modulate = Color.FromHex("#666666");
            ChanceLabel.Visible = false;
        }

        SpliceButton.Disabled = !state.CanSplice;
        EjectAButton.Disabled = !state.HasDiskA;
        EjectBButton.Disabled = !state.HasDiskB;
    }

    private static Color GetRarityColor(PlantGeneRarity r) => r switch
    {
        PlantGeneRarity.Common => Color.FromHex("#BBBBBB"),
        PlantGeneRarity.Uncommon => Color.FromHex("#44CC44"),
        PlantGeneRarity.Rare => Color.FromHex("#4499FF"),
        PlantGeneRarity.Legendary => Color.FromHex("#FF9944"),
        _ => Color.White,
    };
}
