// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.Botany.Genes;
using Content.Shared._Capibara.Botany.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PlantAnalyzerBuiState state)
    {
        // Header
        SpeciesLabel.Text = state.SpeciesName ?? "???";
        if (state.Dead)
        {
            StatusLabel.Text = Loc.GetString("capibara-plant-analyzer-status-dead");
            StatusLabel.Modulate = Color.FromHex("#CC3333");
        }
        else if (state.Harvest)
        {
            StatusLabel.Text = Loc.GetString("capibara-plant-analyzer-status-harvest");
            StatusLabel.Modulate = Color.FromHex("#33CC33");
        }
        else
        {
            StatusLabel.Text = Loc.GetString("capibara-plant-analyzer-status-growing");
            StatusLabel.Modulate = Color.FromHex("#AAAAAA");
        }

        var hpRatio = state.MaxHealth > 0 ? state.Health / state.MaxHealth : 0;
        HealthBarLabel.Text = $"{state.Health:F0}/{state.MaxHealth:F0}";
        HealthBarLabel.Modulate = RatioColor(hpRatio);

        // Vitals (compact 4-column: label value label value)
        VitalsGrid.RemoveAllChildren();
        AddVitalCell(VitalsGrid, Loc.GetString("capibara-plant-analyzer-water"), $"{state.WaterLevel:F0}%", RatioColor(state.WaterLevel / 100f));
        AddVitalCell(VitalsGrid, Loc.GetString("capibara-plant-analyzer-nutrition"), $"{state.NutritionLevel:F0}%", RatioColor(state.NutritionLevel / 100f));
        AddVitalCell(VitalsGrid, Loc.GetString("capibara-plant-analyzer-pests"), $"{state.PestLevel:F1}", InverseColor(state.PestLevel / 10f));
        AddVitalCell(VitalsGrid, Loc.GetString("capibara-plant-analyzer-weeds"), $"{state.WeedLevel:F1}", InverseColor(state.WeedLevel / 10f));
        AddVitalCell(VitalsGrid, Loc.GetString("capibara-plant-analyzer-toxins"), $"{state.Toxins:F0}", InverseColor(state.Toxins / 100f));
        AddVitalCell(VitalsGrid, Loc.GetString("capibara-plant-analyzer-age"), $"{state.Age}", Color.White);

        // Stats (4-column layout: 2 stats per row)
        StatsGrid.RemoveAllChildren();
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-potency"), $"{state.Potency:F1}",
            Loc.GetString("capibara-seed-analyzer-stat-yield"), $"{state.Yield}");
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-lifespan"), $"{state.Lifespan:F0}",
            Loc.GetString("capibara-seed-analyzer-stat-maturation"), $"{state.Maturation:F0}");
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-production"), $"{state.Production:F0}",
            Loc.GetString("capibara-seed-analyzer-stat-endurance"), $"{state.Endurance:F0}");

        // Environment
        EnvGrid.RemoveAllChildren();
        AddStatPair(EnvGrid,
            Loc.GetString("capibara-seed-analyzer-stat-ideal-heat"), $"{state.IdealHeat:F0}K",
            Loc.GetString("capibara-seed-analyzer-stat-ideal-light"), $"{state.IdealLight:F0}");
        AddStatPair(EnvGrid,
            Loc.GetString("capibara-seed-analyzer-stat-water"), $"{state.WaterConsumption:F2}/c",
            Loc.GetString("capibara-seed-analyzer-stat-nutrient"), $"{state.NutrientConsumption:F2}/c");

        // Mutation
        MutationGrid.RemoveAllChildren();
        AddStatPair(MutationGrid,
            Loc.GetString("capibara-plant-analyzer-mutation-level"), $"{state.MutationLevel:F1}",
            Loc.GetString("capibara-plant-analyzer-mutation-mod"), $"x{state.MutationMod:F1}");
        AddStatPair(MutationGrid,
            Loc.GetString("capibara-plant-analyzer-gene-chance"), $"{state.GeneDiscoveryChance:F1}%",
            Loc.GetString("capibara-plant-analyzer-harvest-type"), state.HarvestType);

        // Extra plant traits
        var traitParts = new List<string>();
        if (state.Seedless) traitParts.Add(Loc.GetString("capibara-plant-analyzer-trait-seedless"));
        if (state.Ligneous) traitParts.Add(Loc.GetString("capibara-plant-analyzer-trait-ligneous"));
        if (traitParts.Count > 0)
        {
            AddStatPair(MutationGrid,
                Loc.GetString("capibara-plant-analyzer-traits"), string.Join(", ", traitParts),
                "", "");
        }

        // Chemistry
        ChemContainer.RemoveAllChildren();
        if (state.ChemicalNames.Count > 0)
        {
            foreach (var chem in state.ChemicalNames)
            {
                ChemContainer.AddChild(new Label
                {
                    Text = $"  {chem}",
                    Modulate = Color.FromHex("#88CC88"),
                    Margin = new Thickness(0, 1),
                });
            }
        }
        else
        {
            ChemContainer.AddChild(new Label
            {
                Text = Loc.GetString("capibara-plant-analyzer-no-chemicals"),
                Modulate = Color.FromHex("#666666"),
            });
        }

        // Genome
        GenomeSection.Visible = state.HasGenome;
        if (state.HasGenome)
        {
            InstabilityLabel.Text = Loc.GetString("capibara-seed-analyzer-instability",
                ("value", $"{state.Instability:F0}"));
            InstabilityLabel.Modulate = InstabilityColor(state.Instability);

            GeneSlotsContainer.RemoveAllChildren();

            // Slot summary
            GeneSlotsContainer.AddChild(new Label
            {
                Text = Loc.GetString("capibara-plant-analyzer-slots-summary",
                    ("filled", state.FilledSlots), ("empty", state.EmptySlots), ("max", state.MaxSlots)),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(0, 0, 0, 4),
            });
            for (var i = 0; i < state.GeneSlots.Count; i++)
            {
                GeneSlotsContainer.AddChild(CreateGeneSlotPanel(i + 1, state.GeneSlots[i]));
            }
        }

        // Epigenetics
        EpigeneticsContainer.RemoveAllChildren();
        NoEpigeneticsLabel.Visible = state.EpigeneticNames.Count == 0;
        foreach (var name in state.EpigeneticNames)
        {
            var epiPanel = new PanelContainer
            {
                Margin = new Thickness(0, 1),
            };
            epiPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1A2E2E"),
                ContentMarginLeftOverride = 6,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
                ContentMarginRightOverride = 6,
            };
            epiPanel.AddChild(new Label
            {
                Text = name,
                Modulate = Color.FromHex("#66CCCC"),
            });
            EpigeneticsContainer.AddChild(epiPanel);
        }
    }

    private static void AddVitalCell(GridContainer grid, string label, string value, Color color)
    {
        grid.AddChild(new Label
        {
            Text = label,
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(2, 1),
        });
        grid.AddChild(new Label
        {
            Text = value,
            Modulate = color,
            Margin = new Thickness(0, 1, 6, 1),
        });
    }

    private static void AddStatPair(GridContainer grid, string label1, string val1, string label2, string val2)
    {
        grid.AddChild(new Label
        {
            Text = label1,
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(2, 2),
        });
        grid.AddChild(new Label
        {
            Text = val1,
            Margin = new Thickness(0, 2, 12, 2),
        });
        grid.AddChild(new Label
        {
            Text = label2,
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(2, 2),
        });
        grid.AddChild(new Label
        {
            Text = val2,
            Margin = new Thickness(0, 2, 2, 2),
        });
    }

    private static PanelContainer CreateGeneSlotPanel(int num, GeneSlotData data)
    {
        var panel = new PanelContainer
        {
            Margin = new Thickness(0, 1),
        };

        Color bgColor;
        if (data.Locked)
            bgColor = Color.FromHex("#1A1A1A");
        else if (data.GeneId != null)
            bgColor = GetRarityBgColor(data.Rarity ?? PlantGeneRarity.Common);
        else
            bgColor = Color.FromHex("#12121A");

        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = bgColor,
            BorderColor = data.GeneId != null ? GetRarityColor(data.Rarity ?? PlantGeneRarity.Common).WithAlpha(0.3f) : Color.FromHex("#222222"),
            BorderThickness = new Thickness(3, 0, 0, 0),
            ContentMarginLeftOverride = 8,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
            ContentMarginRightOverride = 6,
        };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        var numLabel = new Label
        {
            Text = $"{num}.",
            MinWidth = 20,
            Modulate = Color.FromHex("#666666"),
        };
        box.AddChild(numLabel);

        if (data.Locked)
        {
            box.AddChild(new Label
            {
                Text = Loc.GetString("capibara-seed-analyzer-slot-locked"),
                Modulate = Color.FromHex("#554444"),
            });
        }
        else if (data.GeneId == null)
        {
            box.AddChild(new Label
            {
                Text = Loc.GetString("capibara-seed-analyzer-slot-empty"),
                Modulate = Color.FromHex("#444455"),
            });
        }
        else
        {
            var rarityColor = GetRarityColor(data.Rarity ?? PlantGeneRarity.Common);
            box.AddChild(new Label
            {
                Text = data.GeneName ?? "???",
                Modulate = rarityColor,
                HorizontalExpand = true,
            });
            box.AddChild(new Label
            {
                Text = $"[{data.Rarity}]",
                Modulate = rarityColor.WithAlpha(0.6f),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Right,
            });
        }

        panel.AddChild(box);
        return panel;
    }

    private static Color RatioColor(float ratio)
    {
        if (ratio > 0.6f) return Color.FromHex("#44BB44");
        if (ratio > 0.3f) return Color.FromHex("#BBBB44");
        return Color.FromHex("#BB4444");
    }

    private static Color InverseColor(float ratio)
    {
        if (ratio < 0.2f) return Color.FromHex("#44BB44");
        if (ratio < 0.5f) return Color.FromHex("#BBBB44");
        return Color.FromHex("#BB4444");
    }

    private static Color GetRarityColor(PlantGeneRarity rarity) => rarity switch
    {
        PlantGeneRarity.Common => Color.FromHex("#BBBBBB"),
        PlantGeneRarity.Uncommon => Color.FromHex("#44CC44"),
        PlantGeneRarity.Rare => Color.FromHex("#4499FF"),
        PlantGeneRarity.Legendary => Color.FromHex("#FF9944"),
        _ => Color.White,
    };

    private static Color GetRarityBgColor(PlantGeneRarity rarity) => rarity switch
    {
        PlantGeneRarity.Common => Color.FromHex("#161618"),
        PlantGeneRarity.Uncommon => Color.FromHex("#14201A"),
        PlantGeneRarity.Rare => Color.FromHex("#141A24"),
        PlantGeneRarity.Legendary => Color.FromHex("#201A14"),
        _ => Color.FromHex("#161618"),
    };

    private static Color InstabilityColor(float inst)
    {
        if (inst <= 25f) return Color.FromHex("#44BB44");
        if (inst <= 50f) return Color.FromHex("#BBBB44");
        if (inst <= 75f) return Color.FromHex("#CC7733");
        return Color.FromHex("#CC3333");
    }
}
