// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.Botany.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantCentrifugeWindow : FancyWindow
{
    public event Action? OnProcess;
    public event Action? OnEject;

    public PlantCentrifugeWindow()
    {
        RobustXamlLoader.Load(this);
        ProcessButton.OnPressed += _ => OnProcess?.Invoke();
        EjectButton.OnPressed += _ => OnEject?.Invoke();
    }

    public void UpdateState(PlantCentrifugeBuiState state)
    {
        if (state.HasProduce)
        {
            StatusLabel.Text = Loc.GetString("capibara-plant-centrifuge-ready", ("name", state.ProduceName ?? "???"));
            StatusLabel.Modulate = Color.FromHex("#44BB44");
        }
        else
        {
            StatusLabel.Text = Loc.GetString("capibara-plant-centrifuge-no-produce");
            StatusLabel.Modulate = Color.FromHex("#666666");
        }

        ProcessButton.Disabled = !state.CanProcess;
    }
}
