// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Capibara.Botany.Genes;
using Content.Shared._Capibara.Botany.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class SeedAnalyzerWindow : FancyWindow
{
    public event Action? OnEjectPressed;

    public SeedAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
    }

    public void UpdateState(SeedAnalyzerBuiState state)
    {
        NoSeedLabel.Visible = !state.HasSeed;
        ContentScroll.Visible = state.HasSeed;

        if (!state.HasSeed)
            return;

        SpeciesLabel.Text = state.SpeciesName ?? "???";

        // Stats (4-column pairs)
        StatsGrid.RemoveAllChildren();
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-potency"), $"{state.Potency:F1}",
            Loc.GetString("capibara-seed-analyzer-stat-yield"), $"{state.Yield}");
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-lifespan"), $"{state.Lifespan:F0}",
            Loc.GetString("capibara-seed-analyzer-stat-maturation"), $"{state.Maturation:F0}");
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-production"), $"{state.Production:F0}",
            Loc.GetString("capibara-seed-analyzer-stat-endurance"), $"{state.Endurance:F0}");
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-ideal-heat"), $"{state.IdealHeat:F0}K",
            Loc.GetString("capibara-seed-analyzer-stat-ideal-light"), $"{state.IdealLight:F0}");
        AddStatPair(StatsGrid,
            Loc.GetString("capibara-seed-analyzer-stat-water"), $"{state.WaterConsumption:F2}",
            Loc.GetString("capibara-seed-analyzer-stat-nutrient"), $"{state.NutrientConsumption:F2}");

        // Instability
        InstabilityLabel.Text = Loc.GetString("capibara-seed-analyzer-instability",
            ("value", $"{state.Instability:F0}"));
        InstabilityLabel.Modulate = InstabilityColor(state.Instability);

        // Gene slots
        GeneSlotsContainer.RemoveAllChildren();
        for (var i = 0; i < state.GeneSlots.Count; i++)
        {
            GeneSlotsContainer.AddChild(CreateGeneSlotPanel(i + 1, state.GeneSlots[i]));
        }

        // Epigenetics
        EpigeneticsContainer.RemoveAllChildren();
        NoEpigeneticsLabel.Visible = state.EpigeneticNames.Count == 0;
        foreach (var name in state.EpigeneticNames)
        {
            var epiPanel = new PanelContainer { Margin = new Thickness(0, 1) };
            epiPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1A2E2E"),
                ContentMarginLeftOverride = 6, ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2, ContentMarginRightOverride = 6,
            };
            epiPanel.AddChild(new Label { Text = name, Modulate = Color.FromHex("#66CCCC") });
            EpigeneticsContainer.AddChild(epiPanel);
        }
    }

    private static void AddStatPair(GridContainer grid, string l1, string v1, string l2, string v2)
    {
        grid.AddChild(new Label { Text = l1, StyleClasses = { "LabelSubText" }, Margin = new Thickness(2, 2) });
        grid.AddChild(new Label { Text = v1, Margin = new Thickness(0, 2, 12, 2) });
        grid.AddChild(new Label { Text = l2, StyleClasses = { "LabelSubText" }, Margin = new Thickness(2, 2) });
        grid.AddChild(new Label { Text = v2, Margin = new Thickness(0, 2, 2, 2) });
    }

    private static PanelContainer CreateGeneSlotPanel(int num, GeneSlotData data)
    {
        var panel = new PanelContainer { Margin = new Thickness(0, 1) };

        Color bgColor;
        if (data.Locked)
            bgColor = Color.FromHex("#1A1A1A");
        else if (data.GeneId != null)
            bgColor = GetRarityBg(data.Rarity ?? PlantGeneRarity.Common);
        else
            bgColor = Color.FromHex("#12121A");

        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = bgColor,
            BorderColor = data.GeneId != null ? GetRarityColor(data.Rarity ?? PlantGeneRarity.Common).WithAlpha(0.3f) : Color.FromHex("#222222"),
            BorderThickness = new Thickness(3, 0, 0, 0),
            ContentMarginLeftOverride = 8, ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4, ContentMarginRightOverride = 6,
        };

        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        box.AddChild(new Label { Text = $"{num}.", MinWidth = 20, Modulate = Color.FromHex("#666666") });

        if (data.Locked)
            box.AddChild(new Label { Text = Loc.GetString("capibara-seed-analyzer-slot-locked"), Modulate = Color.FromHex("#554444") });
        else if (data.GeneId == null)
            box.AddChild(new Label { Text = Loc.GetString("capibara-seed-analyzer-slot-empty"), Modulate = Color.FromHex("#444455") });
        else
        {
            var c = GetRarityColor(data.Rarity ?? PlantGeneRarity.Common);
            box.AddChild(new Label { Text = data.GeneName ?? "???", Modulate = c, HorizontalExpand = true });
            box.AddChild(new Label { Text = $"[{data.Rarity}]", Modulate = c.WithAlpha(0.6f), StyleClasses = { "LabelSubText" }, HorizontalAlignment = HAlignment.Right });
        }

        panel.AddChild(box);
        return panel;
    }

    private static Color GetRarityColor(PlantGeneRarity r) => r switch
    {
        PlantGeneRarity.Common => Color.FromHex("#BBBBBB"),
        PlantGeneRarity.Uncommon => Color.FromHex("#44CC44"),
        PlantGeneRarity.Rare => Color.FromHex("#4499FF"),
        PlantGeneRarity.Legendary => Color.FromHex("#FF9944"),
        _ => Color.White,
    };

    private static Color GetRarityBg(PlantGeneRarity r) => r switch
    {
        PlantGeneRarity.Common => Color.FromHex("#161618"),
        PlantGeneRarity.Uncommon => Color.FromHex("#14201A"),
        PlantGeneRarity.Rare => Color.FromHex("#141A24"),
        PlantGeneRarity.Legendary => Color.FromHex("#201A14"),
        _ => Color.FromHex("#161618"),
    };

    private static Color InstabilityColor(float i)
    {
        if (i <= 25f) return Color.FromHex("#44BB44");
        if (i <= 50f) return Color.FromHex("#BBBB44");
        if (i <= 75f) return Color.FromHex("#CC7733");
        return Color.FromHex("#CC3333");
    }
}
