import os

base = r'D:\ss14-server-test\Hispania-Station\Resources\Locale\es-ES\_hispania\prototypes\_lavaland'

files = {
    'actions/cursed_heart.ftl': 'ent-ActionPumpCursedHeart = Latido del Corazon\n    .desc = Bombea tu propia sangre para sobrevivir!\n',
    'actions/hierophant_club.ftl': 'ent-ActionHierophantClubTileMovement = Maldicion del Movimiento en Casillas\n    .desc = Hace que el objetivo solo se mueva por casillas.\n\nent-ActionHierophantClubBlink = Parpadeo\n    .desc = Te teletransporta a cualquier posicion a la que puedas llegar fisicamente.\n',
    'actions/megafauna/hierophant.ftl': 'ent-ActionBaseHierophant = accion del hierofante\n\nent-ActionHierophantBox = Caja Expansiva\n    .desc = Genera una caja expansiva en la posicion objetivo.\n\nent-ActionHierophantCrosses = Cruces en Secuencia\n    .desc = Genera una secuencia de cruces en la posicion objetivo.\n\nent-ActionHierophantChasers = Invocar Perseguidores\n    .desc = Invoca perseguidores de casillas del hierofante que se mueven hacia el objetivo.\n\nent-ActionHierophantBlink = Parpadeo\n    .desc = Te teletransporta a la posicion objetivo.\n',
    'actions/types.ftl': 'ent-ActionTogglePKALight = Activar Luz de la PKA\n    .desc = Activa y desactiva la luz de la PKA.\n',
    'catalog/fills/crates/cargo.ftl': 'ent-CrateCargoGatewayLavaland = caja de portal a Lavaland\n    .desc = Permite teletransportarte directamente a Lavaland.\n\nent-CrateCargoClarkeAssembly = caja de montaje Clarke\n    .desc = Por fin te sentiras seguro dentro de esta nueva maquina! Requiere montaje.\n',
    'entities/clothing/ancient_armor.ftl': 'ent-LavalandEquipmentAncientArmor = armadura del predecesor\n    .desc = Armadura antigua completamente hecha de resistentes placas de goliath.\n\nent-LavalandEquipmentAncientArmorHood = casco del predecesor\n    .desc = Casco blindado que recuerda a alguna deidad pagana. Los agujeros para los ojos estan cubiertos de resina duradera. Parece dificil respirar dentro.\n',
    'entities/clothing/explorer_suit.ftl': 'ent-LavalandEquipmentExplorerSuit = traje de explorador\n    .desc = Un traje blindado para explorar entornos hostiles.\n\nent-LavalandEquipmentExplorerHood = capucha de explorador\n    .desc = Una capucha blindada para explorar entornos hostiles.\n\nent-LavalandEquipmentExplorerSuitReinforced1 = traje de explorador reforzado\n    .desc = Un traje blindado para explorar entornos hostiles. Ligeramente reforzado con placas de goliath.\n\nent-LavalandEquipmentExplorerHoodReinforced1 = capucha de explorador reforzada\n    .desc = Una capucha blindada para explorar entornos hostiles. Ligeramente reforzada con placas de goliath.\n\nent-LavalandEquipmentExplorerSuitReinforced2 = traje de explorador reforzado\n    .desc = Un traje blindado para explorar entornos hostiles. Mayormente reforzado con placas de goliath.\n\nent-LavalandEquipmentExplorerHoodReinforced2 = capucha de explorador reforzada\n    .desc = Una capucha blindada para explorar entornos hostiles. Mayormente reforzada con placas de goliath.\n\nent-LavalandEquipmentExplorerSuitReinforced3 = traje de explorador reforzado\n    .desc = Un traje blindado para explorar entornos hostiles. Completamente reforzado con placas de goliath.\n\nent-LavalandEquipmentExplorerHoodReinforced3 = capucha de explorador reforzada\n    .desc = Una capucha blindada para explorar entornos hostiles. Completamente reforzada con placas de goliath.\n',
    'entities/clothing/uniforms/jumpsuits.ftl': 'ent-ClothingUniformJumpsuitShaftMiner = mono del minero\n    .desc = Un elegante mono con un robusto par de overoles. Parece algo quemado.\n',
    'entities/markers/spawners/entityshapes/hierophant.ftl': 'ent-BaseHierophantShape = generador de ataque del hierofante\n\nent-HierophantShapeCrossBishop = generador de ataque cruzado alfil del hierofante\n\nent-HierophantShapeCrossRook = generador de ataque cruzado torre del hierofante\n\nent-HierophantShapeCrossQueen = generador de ataque cruzado reina del hierofante\n\nent-HierophantShapeBlink = generador de ataque parpadeo del hierofante\n\nent-HierophantShapeBlinkSafe = generador de ataque parpadeo seguro del hierofante\n\nent-HierophantShapeBoxExpanding = generador de ataque caja expansiva del hierofante\n\nent-HierophantShapeCrossSequence = generador de ataque cruzado en secuencia del hierofante\n',
    'entities/markers/spawners/entityshapes/hierophant_club.ftl': 'ent-HierophantClubShapeExpandingBox = generador de ataque caja expansiva del hierofante\n\nent-HierophantClubShapeRandomCross = generador de ataque cruzado en secuencia del hierofante\n',
    'entities/markers/spawners/jobs.ftl': 'ent-SpawnPointShaftMiner = minero\n',
    'entities/markers/spawners/megafauna.ftl': 'ent-SpawnMobHierophant = Generador de Hierofante\n',
    'entities/markers/spawners/random/mobs.ftl': 'ent-SpawnerRandomMobLavaland = generador de mob pesado de Lavaland\n\nent-SpawnerRandomLightMobLavaland = generador de mob ligero de Lavaland\n',
    'entities/markers/spawners/random/tendril.ftl': 'ent-SpawnerRandomTendrilLavaland = generador de tendril\n',
    'entities/markers/spawners/random/weapons_loot.ftl': 'ent-CrusherWeaponLootSpawner = generador de arma trituradora\n\nent-CrusherUpgradeLootSpawner = generador de mejora trituradora\n\nent-ProtoKineticWeaponLootSpawner = generador de arma proto-cinetica\n\nent-ProtoKineticWeaponSpaceLootSpawner = generador de arma proto-cinetica espacial\n\nent-ProtoKineticUpgradeLootSpawner = generador de mejora proto-cinetica\n\nent-SecondaryKineticWeaponLootSpawner = generador de arma cinetica secundaria\n\nent-LavalandWeaponLootSpawner = generador de botin de armas de Lavaland\n',
    'entities/mobs/bosses/ashdrake.ftl': 'ent-LavalandBossAshDrake = drake de ceniza\n    .desc = Guardian de la Necropolis.\n',
    'entities/mobs/bosses/bubblegum.ftl': 'ent-LavalandBossBubblegum = Bubblegum\n    .desc = En lo que hace las veces de jerarquia entre los demonios matadores, este es el rey.\n',
    'entities/mobs/bosses/colossus.ftl': 'ent-LavalandBossColossus = Coloso\n    .desc = Una criatura monstruosa protegida por un escudo pesado.\n',
    'entities/mobs/bosses/hierophant.ftl': 'ent-MobHierophant = hierofante\n    .desc = Un enorme mazo metalico que flota en el aire como si estuviera esperando. Te hara bailar al ritmo que marca.\n',
    'entities/mobs/bosses/megalegion.ftl': 'ent-LavalandBossMegaLegion = Legion\n    .desc = Uno de muchos.\n',
    'entities/mobs/elites/elite.ftl': 'ent-LavalandEliteBase = Elite\n    .desc = Un monstruo de elite, encontrado en uno de los extranos tumores de Lavaland.\n\nent-LavalandEliteLegionnaire = Legionario\n    .desc = Un esqueleto imponente que encarna el aterrador poder de Legion.\n\nent-LavalandElitePandora = Pandora\n    .desc = Una gran caja magica con poder y diseno similares al Hierofante. Una vez que se abre, no es facil cerrarla.\n\nent-LavalandEliteHerald = Heraldo\n    .desc = Una bestia monstruosa que dispara proyectiles letales a las amenazas y presas.\n\nent-LavalandEliteGoliathBroodmother = Reina Madre\n    .desc = Un ejemplo de dimorfismo sexual, esta hembra goliath tiene un aspecto muy diferente al de los machos de su especie. Sin embargo, es igual de peligrosa, si no mas.\n',
    'entities/mobs/goliath.ftl': 'ent-MobLavalandGoliathAncient = goliath antiguo\n',
    'entities/mobs/legion.ftl': 'ent-MobLegion = humanoide legion\n    .desc = Todavia puedes ver lo que una vez fue un humano bajo la masa cambiante de corrupcion.\n\nent-MobLegionSkull = calavera legion\n    .desc = Un fragmento de la legion original, reagrupandose detras de su original. Una sola no es gran amenaza, pero...\n',
    'entities/mobs/mobs.ftl': 'ent-LavalandMobAshWhelp = Cria de Ceniza\n    .desc = La cria de un drake de ceniza, debil en comparacion pero aun aterradora.\n\nent-LavalandMobBrimdemon = Brimdemon\n    .desc = Una criatura volatil que parece un enorme craneo con cuernos. Su respuesta a casi cualquier estimulo es soltar un rayo de energia infernal.\n\nent-LavalandMobLegionMonkey = Chusma\n    .desc = Puedes ver lo que antes era un mono bajo la masa cambiante de corrupcion. No tiene suficiente biomasa para reproducirse.\n',
    'entities/objects/consumable/cactus_fruit.ftl': 'ent-FoodMealCactusFruit = fruta de cactus\n    .desc = Una fruta de cactus cubierta de una gruesa piel rojiza. Y algo de ceniza.\n',
    'entities/objects/consumable/seraka_cap.ftl': 'ent-FoodMealSerakaCap = sombrerillo seraka\n    .desc = Setas pequenas y muy sabrosas originalmente nativas de Tizira.\n',
    'entities/objects/decoration/flora.ftl': 'ent-AshBush = arbusto polvoriento\n    .desc = Un arbusto cubierto de ceniza. Puede parecer muerto, pero en realidad esta vivo!\n',
    'entities/objects/decoration/mushrooms.ftl': 'ent-Lavashroom = lavashroom\n    .desc = Un hongo silvestre al que le gusta crecer en entornos calidos y humedos.\n',
    'entities/objects/decoration/seraka_mushroom.ftl': 'ent-SerakaMushroom = setas seraka\n    .desc = Un pequeno grupo de setas seraka. Deben de haber venido con los lagartos de ceniza.\n',
    'entities/objects/decoration/trees.ftl': 'ent-FloraAshtree = arbol de ceniza\n',
    'entities/objects/devices/computer.ftl': 'ent-LavalandShuttleConsoleCircuitboard = placa de consola del transbordador minero\n    .desc = Una placa de circuito impreso para una consola del transbordador minero.\n',
    'entities/objects/devices/flatpack.ftl': 'ent-GatewayFlatpackLavaland = flatpack de portal a Lavaland\n    .desc = Un flatpack usado para crear mediante bluespace un portal para viajar a Lavaland.\n',
    'entities/objects/devices/pda.ftl': 'ent-MinerPDA = PDA de minero\n    .desc = Huele a ceniza.\n',
    'entities/objects/materials/ore.ftl': 'ent-ArtifactFragmentOre = fragmento de mineral artefacto\n\nent-GoldOreUnprocessed = mineral de oro sin procesar\n\nent-GoldOre1Unprocessed = mineral de oro sin procesar\n\nent-DiamondOreUnprocessed = mineral de diamante sin procesar\n\nent-DiamondOre1Unprocessed = mineral de diamante sin procesar\n\nent-SteelOreUnprocessed = mineral de hierro sin procesar\n\nent-SteelOre1Unprocessed = mineral de hierro sin procesar\n\nent-SteelOre60Unprocessed = mineral de hierro sin procesar\n\nent-SteelOre90Unprocessed = mineral de hierro sin procesar\n\nent-PlasmaOreUnprocessed = mineral de plasma sin procesar\n\nent-PlasmaOre1Unprocessed = mineral de plasma sin procesar\n\nent-SilverOreUnprocessed = mineral de plata sin procesar\n\nent-SilverOre1Unprocessed = mineral de plata sin procesar\n\nent-SpaceQuartzUnprocessed = cuarzo espacial sin procesar\n\nent-SpaceQuartz1Unprocessed = cuarzo espacial sin procesar\n\nent-SpaceQuartz60Unprocessed = cuarzo espacial sin procesar\n\nent-SpaceQuartz90Unprocessed = cuarzo espacial sin procesar\n\nent-UraniumOreUnprocessed = mineral de uranio sin procesar\n\nent-UraniumOre1Unprocessed = mineral de uranio sin procesar\n\nent-BananiumOreUnprocessed = mineral de bananio sin procesar\n\nent-BananiumOre1Unprocessed = mineral de bananio sin procesar\n\nent-CoalUnprocessed = carbon sin procesar\n\nent-Coal1Unprocessed = carbon sin procesar\n\nent-Coal5Unprocessed = carbon sin procesar\n\nent-Coal10Unprocessed = carbon sin procesar\n\nent-Coal15Unprocessed = carbon sin procesar\n\nent-Coal60Unprocessed = carbon sin procesar\n\nent-Coal90Unprocessed = carbon sin procesar\n\nent-ArtifactFragmentOreUnprocessed = fragmento de mineral artefacto sin procesar\n\nent-ArtifactFragmentOre1Unprocessed = fragmento de mineral artefacto sin procesar\n',
    'entities/objects/materials/specific.ftl': 'ent-MaterialWatcherWing = ala de observador\n    .desc = Son resistentes y aun asi se fusionan facilmente entre si, deberia ser un gran material para nuevas herramientas.\n\nent-MaterialWatcherMagmaWing = ala de magma de observador\n    .desc = Un ala con magma fluyendo en su interior. Son resistentes y aun asi se fusionan facilmente entre si, deberia ser un gran material para nuevas herramientas.\n\nent-MaterialWatcherIceWing = ala de hielo de observador\n    .desc = Un ala hecha de hielo, pero que por alguna razon se niega a derretirse. Son resistentes y aun asi se fusionan facilmente entre si, deberia ser un gran material para nuevas herramientas.\n\nent-MaterialLegionSkull = calavera legion\n    .desc = Una calavera gris y deformada de un humanoide hace mucho desaparecido. Por un breve momento, sentiste que te miraba directamente al alma.\n',
    'entities/objects/misc/identification_cards.ftl': 'ent-MinerIDCard = tarjeta de identidad de minero\n',
    'entities/objects/misc/implants.ftl': 'ent-DeathRattleLavalandImplant = implante de estertores de muerte para Lavaland\n    .desc = Este implante informara al canal de radio de Suministros en caso de que el usuario muera. Solo funciona en la superficie de Lavaland e indica las coordenadas exactas de la muerte.\n',
    'entities/objects/projectiles/hierophant_tiles.ftl': 'ent-LavalandHierophantSquare = casilla del hierofante\n\nent-LavalandHierophantChaser = perseguidor del hierofante\n',
    'entities/objects/projectiles/rude_buster.ftl': 'ent-ProjectileRudeBuster = rude buster\n    .desc = Un potente proyectil magico que concentra toda la voluntad del usuario en un solo golpe poderoso.\n',
    'entities/objects/specific/medical/hypospray.ftl': 'ent-SurvivalMedipen = medipen de supervivencia\n    .desc = Un coctel de potentes quimicos curativos. Contiene Leporazina y Balsamo del Minero. Cura el dano lentamente y estabiliza la temperatura corporal. Puedes sufrir una sobredosis si usas mas de uno seguido.\n\nent-LuxuryMedipen = medipen de lujo\n    .desc = La tecnologia de bluespace de ultima generacion permitio a Nanotrasen compactar 180u de volumen en un solo medipen. Contiene quimicos raros y potentes para ayudar en la exploracion de entornos hostiles. Los quimicos son relativamente daninos y menos efectivos fuera de baja presion.\n',
    'entities/objects/specific/salvage/jaunter.ftl': 'ent-LavalandJaunter = jaunter\n    .desc = Un dispositivo complejo que funciona con tecnologia de bluespace, capaz de teletransportarte fuera de zonas de peligro. Deberias llevarlo encima cuando camines cerca de un abismo.\n\nent-LavalandJaunterRecharging = jaunter experimental\n',
}

for rel_path, content in files.items():
    full_path = os.path.join(base, rel_path.replace('/', os.sep))
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Written: {rel_path}')

print('Done!')
