# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

station-event-deathsquad-enroute = Todos los contratos con la tripulación han sido rescindidos. Se ordena a Seguridad que deponga las armas, y se requiere que la antigua tripulación se rinda a Nanotrasen. El incumplimiento resultará en pena capital. El Mando debe rendirse pacíficamente primero, para dar ejemplo a la antigua tripulación.
station-event-emergencyresponseteam-generic-enroute = Equipo de Respuesta de Emergencia en camino. Gloria a Nanotrasen.
station-event-cburn-enroute = Una amenaza biológica o virus ha hecho necesario desplegar un ERT CBURN. Se recomienda encarecidamente a la tripulación que se ponga en cuarentena junto con los demás; se sugiere al departamento médico que cierre sus puertas con cerrojo salvo indicación contraria del personal de Mando o miembros del ERT. Se aconseja a los miembros de la tripulación y Conserjes que lleven trajes biológicos, mascarillas protectoras y guantes para evitar el riesgo de propagación de virus.
station-event-emergencyresponseteam-engineering-enroute = Un problema estructural que no se puede contener fácilmente en tu estación ha llegado a nuestra atención. Se ha desplegado un ERT de Ingeniería para tratar dicho problema; los miembros del ERT de Ingeniería quedan oficialmente por encima del Ingeniero Jefe y del Capitán al tratar el problema estructural.
station-event-emergencyresponseteam-security-enroute = El Mando Central ha considerado que la situación justifica un equipo de 5 Miembros del ERT de Seguridad. La cadena de mando se actualiza oficialmente para que los miembros del ERT estén por encima del capitán mientras están desplegados. Los civiles deben mantenerse al margen y permitir que el ERT, el Mando y Seguridad se encarguen de la(s) amenaza(s).
station-event-emergencyresponseteam-medical-enroute = Una catástrofe masiva ha justificado el despliegue de un ERT Médico. La estructura de mando de Médica se ha actualizado para que los miembros desplegados del ERT Médico estén por encima del Jefe de Medicina y del Capitán en situaciones médicas. Se sugiere que los miembros del ERT y Médica trabajen juntos; los miembros del ERT deben permanecer en médica a menos que sea inseguro o esté lleno.
station-event-emergencyresponseteam-chaplain-enroute = Se han detectado grandes cantidades de actividades mágicas no autorizadas a bordo de la estación. Se ha desplegado un equipo especial de respuesta de emergencia.
