// SPDX-FileCopyrightText: 2025 Capibara Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Capibara.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Capibara.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class SalaryConsoleWindow : FancyWindow
{
    public event Action<int, int>? OnUpdateSalary;
    public event Action? OnInsert;
    public event Action? OnEject;

    // Track which departments are collapsed — all start collapsed
    private readonly HashSet<string> _collapsedDepartments = new();
    private bool _initialCollapseApplied;

    public SalaryConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        InsertButton.OnPressed += _ => OnInsert?.Invoke();
        EjectButton.OnPressed += _ => OnEject?.Invoke();
    }

    public void UpdateState(SalaryConsoleState state)
    {
        // Auth status
        if (!state.HasPrivilegedId)
        {
            AuthLabel.Text = Loc.GetString("capibara-salary-console-insert-id-prompt");
            AuthLabel.FontColorOverride = null;
        }
        else if (!state.IsAuthorized)
        {
            AuthLabel.Text = Loc.GetString("capibara-salary-console-not-authorized");
            AuthLabel.FontColorOverride = Color.FromHex("#CC0000");
        }
        else
        {
            AuthLabel.Text = Loc.GetString("capibara-salary-console-authorized", ("name", state.PrivilegedIdName ?? ""));
            AuthLabel.FontColorOverride = Color.FromHex("#00CC00");
        }

        // Payroll status
        PayrollStatusLabel.Text = state.SalariesCutOff
            ? Loc.GetString("capibara-salary-console-payroll-frozen")
            : Loc.GetString("capibara-salary-console-payroll-active");
        PayrollStatusLabel.FontColorOverride = state.SalariesCutOff
            ? Color.FromHex("#CC0000")
            : Color.FromHex("#00CC00");

        // Insert/Eject visibility
        InsertButton.Visible = !state.HasPrivilegedId;
        EjectButton.Visible = state.HasPrivilegedId;

        // Freeze warning banner
        FreezePanel.Visible = state.SalariesCutOff;

        // Rebuild employee list grouped by department
        EmployeeList.RemoveAllChildren();

        // Group employees by department
        var grouped = state.Employees
            .GroupBy(e => e.DepartmentName ?? Loc.GetString("capibara-salary-console-dept-unknown"))
            .OrderBy(g => g.First().DepartmentWeight == int.MaxValue ? int.MaxValue : -g.First().DepartmentWeight)
            .ToList();

        // On first load, collapse all departments
        if (!_initialCollapseApplied)
        {
            _initialCollapseApplied = true;
            foreach (var g in grouped)
                _collapsedDepartments.Add(g.Key);
        }

        foreach (var deptGroup in grouped)
        {
            var deptName = deptGroup.Key;
            var employees = deptGroup.ToList();
            var deptColor = Color.FromHex(employees[0].DepartmentColor ?? "#888888");
            var isCollapsed = _collapsedDepartments.Contains(deptName);

            // Department header — dark background tinted with dept color for readability
            var totalSalary = employees.Sum(e => e.SalaryOverride ?? e.BaseSalary);
            var arrowText = isCollapsed ? "▶" : "▼";

            // Use a dark tinted background so colored text is always readable
            var headerBg = new Color(
                (byte) (deptColor.RByte * 0.15f),
                (byte) (deptColor.GByte * 0.15f),
                (byte) (deptColor.BByte * 0.15f),
                200);
            var headerBorderColor = deptColor.WithAlpha(0.4f);

            var headerPanel = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(0, 2, 0, 0),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = headerBg,
                    BorderColor = headerBorderColor,
                    BorderThickness = new Thickness(1),
                },
            };

            var headerBtn = new Button
            {
                HorizontalExpand = true,
                ModulateSelfOverride = Color.White.WithAlpha(0f), // transparent button
            };

            var headerRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            headerRow.AddChild(new Label
            {
                Text = arrowText,
                FontColorOverride = deptColor,
                MinWidth = 18,
            });
            headerRow.AddChild(new Label
            {
                Text = $"{deptName} ({employees.Count})",
                FontColorOverride = deptColor,
                HorizontalExpand = true,
                StyleClasses = { "LabelKeyText" },
            });
            headerRow.AddChild(new Label
            {
                Text = Loc.GetString("capibara-salary-console-dept-total", ("total", totalSalary)),
                FontColorOverride = Color.FromHex("#AAAAAA"),
            });

            headerBtn.AddChild(headerRow);
            headerPanel.AddChild(headerBtn);

            // Click to toggle collapse
            var capturedDeptName = deptName;
            var capturedState = state;
            headerBtn.OnPressed += _ =>
            {
                if (_collapsedDepartments.Contains(capturedDeptName))
                    _collapsedDepartments.Remove(capturedDeptName);
                else
                    _collapsedDepartments.Add(capturedDeptName);

                UpdateState(capturedState);
            };

            EmployeeList.AddChild(headerPanel);

            if (isCollapsed)
                continue;

            // Column headers for this department
            var colHeader = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(6, 2),
            };
            colHeader.AddChild(new Label
            {
                Text = Loc.GetString("capibara-salary-console-header-name"),
                StyleClasses = { "LabelSubText" },
                MinWidth = 150,
                HorizontalExpand = true,
            });
            colHeader.AddChild(new Label
            {
                Text = Loc.GetString("capibara-salary-console-header-job"),
                StyleClasses = { "LabelSubText" },
                MinWidth = 120,
                HorizontalExpand = true,
            });
            colHeader.AddChild(new Label
            {
                Text = Loc.GetString("capibara-salary-console-header-salary"),
                StyleClasses = { "LabelSubText" },
                MinWidth = 70,
            });
            colHeader.AddChild(new Label
            {
                Text = Loc.GetString("capibara-salary-console-header-balance"),
                StyleClasses = { "LabelSubText" },
                MinWidth = 70,
            });
            if (state.IsAuthorized)
            {
                colHeader.AddChild(new Control { MinWidth = 130 });
            }
            EmployeeList.AddChild(colHeader);

            // Employee rows
            var alternate = false;
            foreach (var employee in employees)
            {
                var row = new PanelContainer();
                if (alternate)
                {
                    row.PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = Color.FromHex("#FFFFFF").WithAlpha(0.03f),
                    };
                }
                alternate = !alternate;

                var rowContent = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Margin = new Thickness(6, 2),
                };

                rowContent.AddChild(new Label
                {
                    Text = employee.FullName,
                    MinWidth = 150,
                    HorizontalExpand = true,
                });
                rowContent.AddChild(new Label
                {
                    Text = employee.JobTitle ?? "-",
                    MinWidth = 120,
                    HorizontalExpand = true,
                });

                // Salary display
                var effectiveSalary = employee.SalaryOverride ?? employee.BaseSalary;
                var salaryText = employee.SalaryOverride != null
                    ? $"{effectiveSalary}*"
                    : effectiveSalary.ToString();
                rowContent.AddChild(new Label
                {
                    Text = salaryText,
                    MinWidth = 70,
                    FontColorOverride = employee.SalaryOverride != null
                        ? Color.FromHex("#FFCC00")
                        : null,
                });

                rowContent.AddChild(new Label
                {
                    Text = $"{employee.CurrentBalance}",
                    MinWidth = 70,
                });

                if (state.IsAuthorized)
                {
                    var inputBox = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        MinWidth = 130,
                    };
                    var input = new LineEdit
                    {
                        PlaceHolder = effectiveSalary.ToString(),
                        MinWidth = 70,
                    };
                    var setBtn = new Button
                    {
                        Text = Loc.GetString("capibara-salary-console-set"),
                        MinWidth = 50,
                        StyleClasses = { "OpenRight" },
                    };

                    var capturedId = employee.AccountId;
                    setBtn.OnPressed += _ =>
                    {
                        if (int.TryParse(input.Text, out var newSalary) && newSalary >= 0)
                        {
                            OnUpdateSalary?.Invoke(capturedId, newSalary);
                            input.Text = "";
                        }
                    };

                    inputBox.AddChild(input);
                    inputBox.AddChild(setBtn);
                    rowContent.AddChild(inputBox);
                }

                row.AddChild(rowContent);
                EmployeeList.AddChild(row);
            }
        }
    }
}
